[package]
name = "vuck"
version = "1.0.0"
authors = ["Josep Marcello <jspmarcello@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "^1.4.0"