[package]
name = "notal_interpreter"
version = "0.1.0"
authors = ["Josep Marcello <jspmarcello@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
